/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_yj_cruor_testing_main_ScanDisplayActivity */

#ifndef _Included_com_yj_cruor_testing_main_ScanDisplayActivity
#define _Included_com_yj_cruor_testing_main_ScanDisplayActivity
#ifdef __cplusplus
extern "C" {
#endif
#undef com_yj_cruor_testing_main_ScanDisplayActivity_REQUEST_ENABLE_BT
#define com_yj_cruor_testing_main_ScanDisplayActivity_REQUEST_ENABLE_BT 1L
#undef com_yj_cruor_testing_main_ScanDisplayActivity_REQUEST_PARAM
#define com_yj_cruor_testing_main_ScanDisplayActivity_REQUEST_PARAM 2L
/*
 * Class:     com_yj_cruor_testing_main_ScanDisplayActivity
 * Method:    process_Data
 * Signature: ([D)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_com_yj_cruor_1testing_main_ScanDisplayActivity_process_1Data
  (JNIEnv *, jobject, jdoubleArray);

#ifdef __cplusplus
}
#endif
#endif
