/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_yj_cruor_testing_main_ScanDisplayActivity_MyHandler */

#ifndef _Included_com_yj_cruor_testing_main_ScanDisplayActivity_MyHandler
#define _Included_com_yj_cruor_testing_main_ScanDisplayActivity_MyHandler
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
